#!/bin/bash
#
#  |==========================================================|
#  • Autoscript AIO Lite Menu By VnzVM
#  • Vnz Project Developer @VnzVM | @VnzPro | @xhidrolic
#  • Copyright 2024 18 Marc Indonesia [ Sragen ]
#  |==========================================================|
#
rest() {
clear
echo "This Feature Can Only Be Used According To Vps Data With This Autoscript"
echo "Please input link to your vps data backup file."
read -rp "Link File: " -e url
cd /root
wget -O backup.zip "$url"
unzip backup.zip
rm -f backup.zip
sleep 1
echo "Tengah Melakukan Backup Data"
cd /root/backup
cp passwd /etc/
cp group /etc/
cp shadow /etc/
cp gshadow /etc/
cp -r xray /etc/
cp -r funny /etc/
cp -r noobzvpns /etc/
clear
cd
rm -rf /root/backup
rm -f backup.zip
clear
echo "Telah Berjaya Melakukan Backup"
}

restf() {
cd /root
file="backup.zip"
if [ -f "$file" ]; then
echo "$file ditemukan, melanjutkan proses..."
sleep 2
clear
unzip backup.zip
rm -f backup.zip
sleep 1
echo "Tengah Melakukan Backup Data"
cd /root/backup
cp passwd /etc/
cp group /etc/
cp shadow /etc/
cp gshadow /etc/
cp -r xray /etc/
cp -r funny /etc/
cp -r noobzvpns /etc/
cp -r hysteria /etc/
cp -r slowdns /etc/
cp -r volt /etc/
clear
cd
rm -rf /root/backup
rm -f backup.zip
clear
echo "Telah Berjaya Melakukan Backup"
else
    echo "Error: File $file Not Found"
fi
}

clear

backupmenuu() {
clear
echo "
============================
Menu Backup Data VPN in VpS
============================

1. Backup Your Data VPN
2. Restore With Link Backup
3. Restore With SFTP / Termius
==============================
Press CTRL + C / X to Exit Menu
"
read -p "Input Valid Number Option: " mla
case $mla in
1) clear ; backup ;;
2) clear ; rest ;;
3) clear ; restf ;;
x) exit ; menu ;;
*) echo " Please Input Valid Number " ; backupmenuu ;;
esac
}

backupmenuu
