#!/bin/bash
send_logg() {
TEKS="
Lock SSH Account Multilogin
===========================
Username: ${user}
Login IP: ${cekcek} / ${iplimit}
Akun Terkunci Selama 15menit
==========================="
CHATID=$(cat /etc/funny/.chatid)
KEY=$(cat /etc/funny/.keybot)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
curl -s --max-time $TIME -d "chat_id=$CHATID&text=$TEKS" $URL
clear
}

mulog=$(mesinssh)
date=$(date)
data=( `ls /etc/funny/limit/ssh/ip`)

for user in "${data[@]}"
do
    iplimit=$(cat /etc/funny/limit/ssh/ip/$user)
    cekcek=$(echo -e "$mulog" | grep $user | wc -l)

    if [[ $cekcek -gt $iplimit ]]; then
        nais=3
        passwd -l "$user" > /dev/null
        send_logg

        echo "passwd -u $user" | at now + 10 minutes > /dev/null
    else
        echo > /dev/null
    fi

    sleep 0.1
done

echo > /dev/null

clear
